language: node_js

node_js:
  - "8"

sudo: false

branches:
   only:
   - master
   
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search 

script:
  - npm run test-ci-travis

